name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install Cordova CLI
      run: npm install -g cordova@latest
    
    - name: Check project structure
      run: |
        echo "=== Project structure ==="
        ls -la
        echo "=== Looking for config.xml ==="
        find . -name "config.xml" -type f
        echo "=== Looking for package.json ==="
        find . -name "package.json" -type f
    
    - name: Install dependencies
      run: |
        if [ -f "package.json" ]; then
          npm install
        else
          echo "No package.json found, skipping npm install"
        fi
    
    - name: Add Android platform
      run: |
        if [ -f "config.xml" ]; then
          cordova platform add android@latest
        else
          echo "No config.xml found, cannot add platform"
          exit 1
        fi
    
    - name: Build Android APK
      run: |
        cordova build android --debug
        cordova build android --release --unsigned
    
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: platforms/android/app/build/outputs/apk/debug/*.apk
        if-no-files-found: warn
    
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: platforms/android/app/build/outputs/apk/release/*.apk
        if-no-files-found: warn
